### ISSUE TITLE
service descriptor json file naming

### ISSUE THREAD

**Issue by dgoldensquared** [vert-x3/vertx-redis-service#2]
Please note [service descriptor json file name](https://github.com/vert-x3/vertx-service-factory#service-descriptor) needs to match maven coords for [vertx-maven-service-factory](https://github.com/vert-x3/vertx-maven-service-factory) dynamic deployment to work correctly, see recent [vertx-dev discussion](https://groups.google.com/d/msg/vertx-dev/ecebSprWDRA/O4vtkumTFxcJ)

**Comment by purplefox** [comment]
should be fixed now
